### ISSUE TITLE
Cannot figure out how to make it all working with form_for additional inputs.

### ISSUE THREAD

**Issue by ghost** [sheharyarn/s3_direct_upload_example#1]
@sheharyarn thanks for your work and putting this together!

I am trying to achieve upload with additional data. Lets say I have my model post that has name, description and image attachment. Right now I cannot figure out how I can associate these 2 separate forms: form_for with s3_uploader_form.

Do you mind to update your app and include one more external field (lets say name) that passes values and save it all into DB?

**Comment by sheharyarn** [comment]
I'm not sure what you're asking here.

If you want to upload the file _with_ some additional data (meaning, doing the two things together on pressing the `submit` button), `s3_direct_upload` isn't the way to go. A better option would be to use [`paperclip`](https://github.com/thoughtbot/paperclip), where you can upload/store data in a single form, process the uploaded file in your app using Paperclip and then upload the file to `Amazon S3` from Paperclip in your Model.

---

The second way (which I hope what you're trying to do) is, upload a file from your view to `S3` directly, and store the uploaded file's information as the extra information you're sending through your form. I'm assuming you want to store the uploaded file data in your `model` as a field (probably a `hash`?) and not an `association`.

To do this you need to create two forms in your `view`, something like this:

``` erb
<%= s3_uploader_form class: "s3-uploader", id: "S3uploader" do %>
    <%= file_field_tag :file, multiple: false %>
<% end %>

<%= form_for(@your_resource) do |f| %>
    <%# Hidden fields to store information about uploaded file %>
    <%= hidden_field_tag 'file[name]', nil, id: 'file_name_field' %>
    <%= hidden_field_tag 'file[url]', nil, id: 'file_url_field' %>

    <%# Main Fields and other stuff %>
    <%= f.submit "Save Resource" %>
<% end %>
```

Once your file is uploaded, it won't `POST` back the file data because we skipped the `callback` information. But to retain this information, you can use the [`s3_upload_complete`](https://github.com/waynehoover/s3_direct_upload#successfull-upload) Javascript Event Hook to populate the `hidden_fields` we previously created in our form:

``` coffeescript
$('#S3uploader').bind "s3_upload_complete", (e, content) ->
  $('#file_name_field').val(content.filename)
  $('#file_url_field').val(content.url)
```

In your controller you'll get the file details as a hash of `file`, you can also change them to something like `your_resource[your_file_field][name]`, etc so it gets saved to the resource as `your_file_field` directly.

``` ruby
uploaded_file = params[:file]
puts uploaded_file
# => {"name" => "some_image.png", "url" => "http://bucket.s3.aws.com/some/file/path.png" }
```

As an example here, I used only two fields, but if you read the [`s3_upload_complete`](https://github.com/waynehoover/s3_direct_upload#successfull-upload) documentation, you'll find that you can store information of other fields as well (such as path, size and type). You can also keep the Form's submit button disabled and use this `event hook` to enable it only when a file has been uploaded.

---

Also, I won't modify the code for `s3_direct_upload_example` because it's supposed to be a very basic app to get people started with the `s3_direct_upload` gem. What I've explained above is a _little_ advanced, and not suitable for this repository.

You should RTFM @ [`s3_direct_upload`](https://github.com/waynehoover/s3_direct_upload#), it has a very detailed `README` on doing all of this stuff.

**Comment by ghost** [comment]
@sheharyarn thank you for your time writing it.
Yes, I am referring to the second option. The file uploads directly to S3, while user fill rest of the form and submit it with a hash or something I could refer to for retrieving the image details for post-process.
So then my worker will use it for processing the image (resizing, putting it into right directory on S3 etc).

I managed to add with JS the url to the hidden fields, but for some reason when I saved it all, the image table in database was still "nil". I guess its because I did not adjusted my controller properly.

**Comment by sheharyarn** [comment]
@famousky That's probably because you didn't name the `hidden_field` correctly. In the example above, I'm assuming you're storing the file details as a hash in your database. If that's the case, your hidden_field `names` should be something like this:

``` erb
<%= hidden_field_tag 'your_resource_name[your_file_field_name][name]', nil, id: 'file_name_field' %>
<%= hidden_field_tag 'your_resource_name[your_file_field_name][url]', nil, id: 'file_url_field' %>
```

In the code above, replace `your_resource_name` with the singular of your resource and `your_file_field_name` with the name of your file field (column_name).

Example:

``` erb
<%= hidden_field_tag 'post[image][name]', nil, id: 'file_name_field' %>
<%= hidden_field_tag 'post[image][url]', nil, id: 'file_url_field' %>
```

---

If you are not storing the data as a hash, but individual fields (column names) in your table, for example, `image_url` and `image_name`, you'll have to change it to something like this:

``` erb
<%= hidden_field_tag 'post[image_name]', nil, id: 'file_name_field' %>
<%= hidden_field_tag 'post[image_url]', nil, id: 'file_url_field' %>
```

---

You can always test if your params are being returned the way they should be by rendering them as `json` in your controller action (I'm assuming it's `:create`):

``` ruby
def create
    # Comment out
    # all of your other
    # code and only 
    # paste this:

    render json: params[:post]
end
```

**Comment by sheharyarn** [comment]
I'm going to close this issue, I hope the code above helped.
